"""Shared split logic for the S1 -> S2 handoff.

S1's `pcls` task is not a separate corpus from S2: build_unified_dataframe.py concatenates
the whole S2 frame into S1 with task="pcls", so all 38,086 studies appear in both stages.
Splitting the two stages independently put 1,722 of S2's 1,905 val studies (90.4%) inside
S1's train set.

Fix: S2's val is drawn from the studies S1 held out. S1's own split is not touched.

The S1 val pool is pinned to a manifest rather than recomputed. Every split here is a pure
function of (CSV bytes, seed), and both stage CSVs have been rewritten in place before,
which silently moved the S2 val set once; recomputing at runtime would let a future rebuild
re-introduce the leak with no visible symptom.

Rebuild the manifest (only after deliberately re-splitting S1):
    python -m braindiff.training.splits --rebuild
"""
import hashlib
import os

S1_CSV = "/home/data/BRAIN_DIFF_S1/unified_dataframe_norm.csv"
S2_CSV = "/home/data/BRAIN_DIFF_S2/single_timepoint_final.csv"
MANIFEST = os.path.join(os.path.dirname(__file__), "..", "splits", "s1_val_studies.txt")
SEED = 10
S2_VAL_SIZE = 1905          # keeps the previous val size, so eval cost is unchanged


def study_hash(study_uid: str) -> int:
    """Stable, order-independent hash. Deliberately not Python's hash(), which is
    salted per process, and not row position, which moves when a CSV is rebuilt."""
    return int(hashlib.md5(str(study_uid).encode()).hexdigest()[:8], 16)


def s1_val_pool():
    """The study_uids S1 held out -- the only studies S1 never trained on."""
    path = os.path.abspath(MANIFEST)
    if not os.path.exists(path):
        raise SystemExit(
            f"missing split manifest {path}. Rebuild with: python -m braindiff.training.splits --rebuild")
    with open(path) as f:
        pool = {ln.strip() for ln in f if ln.strip() and not ln.startswith("#")}
    if not pool:
        raise SystemExit(f"split manifest {path} is empty")
    return pool


def s2_val_studies(n: int = S2_VAL_SIZE):
    """S2's validation studies: the n pool members with the smallest study_hash.

    Sorted-and-take-n rather than a modulo threshold, so the count is exact and
    does not drift as the pool changes size.
    """
    pool = s1_val_pool()
    if n > len(pool):
        raise SystemExit(f"asked for {n} val studies but the S1 val pool holds {len(pool)}")
    return set(sorted(pool, key=study_hash)[:n])


def rebuild_manifest():
    """Recompute S1's val pool and write the manifest.

S1 has no study_uid (build_unified_dataframe.py intersects columns and drops it), so pcls
rows are mapped back to S2 through the T1w path, a verified 1:1 key over all 38,086 studies.
    """
    import pandas as pd
    from braindiff.training.train_unified import split_csv   # lazy: pulls in torch

    _, val = split_csv(S1_CSV, SEED)
    val_pcls = val[val["task"] == "pcls"]
    s2 = pd.read_csv(S2_CSV, low_memory=False)
    t1w_to_uid = dict(zip(s2["T1w"], s2["study_uid"]))

    uids = [t1w_to_uid[p] for p in val_pcls["T1w"] if p in t1w_to_uid]
    missing = len(val_pcls) - len(uids)
    if missing:
        raise SystemExit(f"{missing} S1 val pcls rows did not map to an S2 study_uid")

    path = os.path.abspath(MANIFEST)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(f"# S1 val pcls studies -- the pool S2's val is drawn from. DO NOT EDIT BY HAND.\n")
        f.write(f"# generated by trainer/splits.py --rebuild, seed={SEED}\n")
        f.write(f"# s1_csv={S1_CSV} mtime={os.path.getmtime(S1_CSV)}\n")
        f.write(f"# s2_csv={S2_CSV} mtime={os.path.getmtime(S2_CSV)}\n")
        for u in sorted(uids):
            f.write(f"{u}\n")
    print(f"wrote {path}: {len(uids)} study_uids")


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--rebuild", action="store_true")
    a = p.parse_args()
    if a.rebuild:
        rebuild_manifest()
    else:
        pool = s1_val_pool()
        val = s2_val_studies()
        print(f"S1 val pool: {len(pool)}   S2 val: {len(val)}   subset: {val <= pool}")
